"""auth session table

Revision ID: 0035757c52c9
Revises: 
Create Date: 2022-12-09 20:32:59.097891

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0035757c52c9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authsession',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('expired_timestamp', sa.DateTime(), nullable=False),
    sa.Column('presentation_record_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('presentation_request_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('presentation_request_satisfied', sa.Boolean(), nullable=False),
    sa.Column(
        "presentation_request",
        postgresql.JSON(astext_type=sa.Text()),
        nullable=True,
    ),
    sa.Column(
        "request_parameters",
        postgresql.JSON(astext_type=sa.Text()),
        nullable=True,
    ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('authsession')
    # ### end Alembic commands ###
