"""oidc session table

Revision ID: 8760126b20e3
Revises: b510c1eba9f1
Create Date: 2022-12-09 20:08:27.752376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8760126b20e3'
down_revision = 'b510c1eba9f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
